### ISSUE TITLE
robinNanoThumbnail error

### ISSUE THREAD

**Issue by BeansIsFat** [kanocz/3dconfigs#1]
I tried to use the robinNanoThumbnail output filter and got the following error in PrusaSlicer:
```
Post-processing script "~/robinNanoThumbnail/filter.go" on file test.gcode failed.
Error code: 2
Output:
~/robinNanoThumbnail/filter.go: line 1: package: command not found
~/robinNanoThumbnail/filter.go: line 3: syntax error near unexpected token `newline'
~/robinNanoThumbnail/filter.go: line 3: `import ('
```
What can I do to make this work?

**Comment by kanocz** [comment]
@BeansIsFat problem is that this file is source code of application, and need to be compiled before use
you need to install golang compiler (you can download it from https://golang.org/ or do something like `sudo apt install golang` if you're using Debian or Ubuntu) and then do `go build` in folder with `filter.go`
